stages:
  - build
  - test

build:
  stage: build
  script:
    - docker run --rm -v $(pwd):/code:ro -w /code --entrypoint=/code/ci/build.sh bluetab/amazonlinux-phoenix-postgresql:20180226093919
  artifacts:
    untracked: true

test:
  stage: test
  script:
    - docker run --rm -v $(pwd):/code:ro -w /code --entrypoint=/code/ci/test.sh bluetab/amazonlinux-elasticsearch-phoenix-redis:20181004162353
  artifacts:
    untracked: true